name: cherrypick_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - cherrypick
  - cherrypick_flutter
  - cherrypick_annotations
  - cherrypick_generator
  - examples/client_app
  - examples/postly

scripts:
  analyze:
    exec: dart analyze

  format:
    exec: dart format lib

  test:
    exec: flutter test

  upgrade:
    exec: darp pub upgrade 

  drop:
    exec: flutter clean 
