name: cherrypick_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - cherrypick
  - cherrypick_flutter
  - examples/client_app
  - examples/postly

scripts:
  analyze:
    exec: dart analyze

  format:
    exec: dart format

  test:
    exec: flutter test