name: cherrypick_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - cherrypick
  - cherrypick_flutter

scripts:
  analyze:
    exec: dart analyze

  format:
    exec: dart format

  test:
    exec: dart test ./test