name: cherrypick_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - cherrypick
  - cherrypick_flutter
  - cherrypick_annotations
  - cherrypick_generator
  - examples/client_app
  - examples/postly

scripts:
  analyze:
    exec: dart analyze

  format:
    exec: dart format lib

  test:
    exec: flutter test

  codegen:
    run: |
      melos exec --scope="postly" -- dart run build_runner build --delete-conflicting-outputs

  outdated:
    exec: dart pub outdated 

  upgrade:
    exec: dart pub upgrade --major-versions

  drop:
    exec: flutter clean 
