name: dart_di
description: Experimental Dependency Injection library.
version: 0.1.0
author: Sergey Penkovsky <sergey.penkovsky@gmail.com>
homepage: locahost

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8

  mockito: ^5.0.3
