name: cherrypick
description: Cherrypick is a small dependency injection (DI) library for dart/flutter projects.
version: 3.0.0
homepage: https://cherrypick-di.netlify.app
documentation: https://cherrypick-di.netlify.app/docs/intro
repository: https://github.com/pese-git/cherrypick
issue_tracker: https://github.com/pese-git/cherrypick/issues
topics:
  - di
  - ioc
  - dependency-injection
  - dependency-management
  - inversion-of-control

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.6

  mockito: ^5.4.4
  melos: ^6.3.2
