name: cherrypick
description: Cherrypick is a small dependency injection (DI) library for dart/flutter projects.
version: 3.0.0-dev.13
homepage: https://cherrypick-di.dev/
documentation: https://cherrypick-di.dev/docs/intro
repository: https://github.com/pese-git/cherrypick
issue_tracker: https://github.com/pese-git/cherrypick/issues
topics:
  - di
  - ioc
  - dependency-injection
  - dependency-management
  - inversion-of-control

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15

  mockito: ^5.0.6
  melos: ^6.3.2
