name: cherrypick
description: Cherrypick is a small dependency injection (DI) library for dart/flutter projects.
version: 2.0.0
homepage: https://pese-git.github.io/cherrypick-site/
documentation: https://github.com/pese-git/cherrypick/wiki
repository: https://github.com/pese-git/cherrypick
issue_tracker: https://github.com/pese-git/cherrypick/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15

  mockito: ^5.0.6
  melos: ^6.3.2
