name: benchmark_cherrypick
version: 0.1.0
publish_to: none
description: Benchmark for cherrypick core DI library

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cherrypick:
    path: ../cherrypick

dev_dependencies:
  lints: ^5.0.0
  benchmark_harness: ^2.2.2
  benchmark_runner: ^0.0.2
