builders:
  module_generator:
    import: "package:cherrypick_generator/module_generator.dart"
    builder_factories: ["moduleBuilder"]
    build_extensions: {".dart": [".cherrypick.g.dart"]}
    auto_apply: dependents
    required_inputs: ["lib/**"]
    runs_before: []
    build_to: source

targets:
  $default:
    builders:
      cherrypick_generator|module_generator:
        generate_for:
          - lib/**.dart