builders:
  inject_generator:
    import: "package:cherrypick_generator/inject_generator.dart"
    builder_factories: ["injectBuilder"]
    build_extensions: {".dart": [".inject.cherrypick.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  module_generator:
    import: "package:cherrypick_generator/module_generator.dart"
    builder_factories: ["moduleBuilder"]
    build_extensions: {".dart": [".module.cherrypick.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      cherrypick_generator|module_generator:
        generate_for:
          - lib/**.dart
      cherrypick_generator|inject_generator:
        generate_for:
          - lib/**.dart
