name: cherrypick_generator
description: |
  Source code generator for the cherrypick dependency injection system. Processes annotations to generate binding and module code for Dart & Flutter projects.

version: 3.0.1
homepage: https://cherrypick-di.netlify.app
documentation: https://cherrypick-di.netlify.app/docs/intro
repository: https://github.com/pese-git/cherrypick/cherrypick_generator
issue_tracker: https://github.com/pese-git/cherrypick/issues
topics:
  - di
  - ioc
  - dependency-injection
  - dependency-management
  - inversion-of-control

environment:
  sdk: ">=3.6.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  cherrypick_annotations: ^3.0.1
  analyzer: ^7.7.1
  dart_style: ^3.0.0
  build: ^2.4.1
  source_gen: ^2.0.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^5.1.1
  mockito: ^5.4.5
  test: ^1.25.8
  build_test: ^2.1.7
  build_runner: ^2.4.13
