name: cherrypick_generator
description: Code generator for cherrypick annotations
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  cherrypick_annotations: any

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.1.0