name: cherrypick_annotations
description: A starting point for Dart libraries or applications.
version: 1.1.0-dev.0
documentation: https://github.com/pese-git/cherrypick/wiki
repository: https://github.com/pese-git/cherrypick
issue_tracker: https://github.com/pese-git/cherrypick/issues

environment:
  sdk: ">=3.5.2 <4.0.0"

# Add regular dependencies here.
dependencies:
  meta: ^1.15.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
