name: cherrypick_annotations
description: |
  Set of annotations for CherryPick dependency injection library. Enables code generation and declarative DI for Dart & Flutter projects.
version: 3.0.1
homepage: https://cherrypick-di.netlify.app
documentation: https://cherrypick-di.netlify.app/docs/intro
repository: https://github.com/pese-git/cherrypick/cherrypick_annotations
issue_tracker: https://github.com/pese-git/cherrypick/issues
topics:
  - di
  - ioc
  - dependency-injection
  - dependency-management
  - inversion-of-control

environment:
  sdk: ">=3.8.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  meta: ^1.15.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8
