name: cherrypick_annotations
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.2 <4.0.0"

# Add regular dependencies here.
dependencies:
  meta: ^1.15.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
