name: Melos + FVM CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      # Установить fvm
      - name: Install FVM
        run: dart pub global activate fvm

      # Установить Flutter SDK через fvm, если .fvm/fvm_config.json присутствует
      # Альтернатива — выкачать flutter нужной версии напрямую (если workspace Flutter-based)
      - name: Install Flutter version via FVM
        run: fvm install

      # Установить Melos
      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap workspace
        run: fvm flutter pub global run melos bootstrap

      # Если нужен форматирование через melos
      - name: Format
        run: fvm flutter pub global run melos run format

      - name: Analyze all packages
        run: fvm flutter pub global run melos run analyze

      - name: Run all tests
        run: fvm flutter pub global run melos run test
